// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function KeyGenRequest(arg1:string):Promise<any>;

export function QueryData():Promise<any>;
