// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function KeyGenRequest(arg1) {
  return window['go']['main']['App']['KeyGenRequest'](arg1);
}

export function QueryData() {
  return window['go']['main']['App']['QueryData']();
}
