name: Release

on:
  push:
    branches:
      - main  # 或者您的主要分支名称

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build for Windows
        run: wails build -platform windows/amd64
        env:
          CGO_ENABLED: 1

      - name: Build for macOS
        run: wails build -platform darwin/amd64
        env:
          CGO_ENABLED: 1

      - name: Build for Linux
        run: wails build -platform linux/amd64
        env:
          CGO_ENABLED: 1

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/bin/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 