name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            asset_name: gbc-linux-amd64
          - os: macos-latest
            asset_name: gbc-macos-amd64
          - os: windows-latest
            asset_name: gbc-windows-amd64.exe

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Get project info
        id: project_info
        run: |
          PROJECT_NAME=$(cat wails.json | grep "name" | head -1 | awk -F: '{ print $2 }' | sed 's/[", ]//g')
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
          echo "Project name: $PROJECT_NAME"

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev || sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev
          sudo apt-get install -y pkg-config
          pkg-config --modversion webkit2gtk-4.0 || pkg-config --modversion webkit2gtk-4.1

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install pkg-config

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.10.1

      - name: Build with Wails
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig
            pkg-config --list-all | grep webkit
            wails build
          else
            wails build
          fi

      - name: Debug Build Output
        run: |
          echo "Listing build directories:"
          find build -type d
          echo "Listing all build artifacts:"
          find build -type f
          echo "Contents of build/bin:"
          ls -la build/bin || echo "build/bin directory not found"

      - name: Create Release
        if: matrix.os == 'ubuntu-latest'
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set file path
        id: set_file
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            echo "FILE_PATH=build/bin/${{ env.PROJECT_NAME }}.exe" >> $GITHUB_ENV
          else
            echo "FILE_PATH=build/bin/${{ env.PROJECT_NAME }}" >> $GITHUB_ENV
          fi

      - name: Upload artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.FILE_PATH }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }} 