name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Windows
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: windows/amd64
          load: true
          tags: wails-build:windows
          build-args: |
            TARGETOS=windows
            TARGETARCH=amd64

      - name: Build macOS
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: darwin/amd64
          load: true
          tags: wails-build:darwin
          build-args: |
            TARGETOS=darwin
            TARGETARCH=amd64

      - name: Build Linux
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          load: true
          tags: wails-build:linux
          build-args: |
            TARGETOS=linux
            TARGETARCH=amd64

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/bin/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 