name: Build gbc

on: push

jobs:
  build:
    runs-on: ${{ matrix.build.os }}
    env:
      NODE_OPTIONS: --max-old-space-size=4096
    strategy:
      fail-fast: false
      matrix:
        build:
          - platform: linux/amd64
            os: ubuntu-latest
          - platform: windows/amd64
            os: windows-latest
          - platform: darwin/universal
            os: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v3
        with:
          build-name: gbc
          build-platform: ${{ matrix.build.platform }}
          go-version: '1.24.2'
          node-version: '22.14.0'
          wails-version: '2.9.3'
          nsis: false